Models/Efmigrationshistory.cs
using System;
using System.Collections.Generic;

namespace suaBaladaAqui.Models
{
    public partial class Efmigrationshistory
    {
        public string MigrationId { get; set; } = null!;
        public string ProductVersion { get; set; } = null!;
    }
}

Models/ErrorViewModel.cs
namespace suaBaladaAqui.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Evento.cs
using System;
using System.Collections.Generic;

namespace suaBaladaAqui.Models
{
    public partial class Evento
    {
        public int Id { get; set; }
        public string Evento1 { get; set; } = null!;
        public string Imagem { get; set; } = null!;
        public string Atracoes { get; set; } = null!;
        public string Cidade { get; set; } = null!;
        public string Bairro { get; set; } = null!;
        public string Endereco { get; set; } = null!;
        public string LocalName { get; set; } = null!;
        public DateTime DataEvento { get; set; }
        public string FoneContato { get; set; } = null!;
        public string Organizador { get; set; } = null!;
        public string Responsavel { get; set; } = null!;
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;

namespace suaBaladaAqui.Models
{
    public partial class Usuario
    {
        public Usuario(){}
        
        public Usuario(int id, string nome, string login, string senha, string tipo, DateTime dataCadastro)
        {
            Id = id;
            Nome = nome;
            Login = login;
            Senha = senha;
            Tipo = tipo;
            DataCadastro = dataCadastro;
        }

        public int Id { get; set; }
        public string Nome { get; set; } = null!;
        public string Login { get; set; } = null!;
        public string Senha { get; set; } = null!;
        public string Tipo { get; set; } = null!;
        public DateTime DataCadastro { get; set; }
    }
}

Models/suaBaladaAquiContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace suaBaladaAqui.Models
{
    public partial class suaBaladaAquiContext : DbContext
    {
        public suaBaladaAquiContext()
        {
        }

        public suaBaladaAquiContext(DbContextOptions<suaBaladaAquiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Efmigrationshistory> Efmigrationshistories { get; set; } = null!;
        public virtual DbSet<Evento> Eventos { get; set; } = null!;
        public virtual DbSet<Usuario> Usuarios { get; set; } = null!;

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseMySql("server=paineladm.cnljv0sbllba.us-east-1.rds.amazonaws.com;database=paineladministrativo2;uid=chapolinAdm;pwd=27bJT6KBLxAfSR8WycZ4", Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.23-mysql"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("utf8mb4_0900_ai_ci")
                .HasCharSet("utf8mb4");

            modelBuilder.Entity<Efmigrationshistory>(entity =>
            {
                entity.HasKey(e => e.MigrationId)
                    .HasName("PRIMARY");

                entity.ToTable("__efmigrationshistory");

                entity.Property(e => e.MigrationId).HasMaxLength(150);

                entity.Property(e => e.ProductVersion).HasMaxLength(32);
            });

            modelBuilder.Entity<Evento>(entity =>
            {
                entity.ToTable("eventos");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Atracoes).HasColumnName("atracoes");

                entity.Property(e => e.Bairro).HasColumnName("bairro");

                entity.Property(e => e.Cidade).HasColumnName("cidade");

                entity.Property(e => e.DataEvento)
                    .HasMaxLength(6)
                    .HasColumnName("dataEvento");

                entity.Property(e => e.Endereco).HasColumnName("endereco");

                entity.Property(e => e.Evento1).HasColumnName("evento");

                entity.Property(e => e.FoneContato).HasColumnName("foneContato");

                entity.Property(e => e.Imagem).HasColumnName("imagem");

                entity.Property(e => e.LocalName).HasColumnName("localName");

                entity.Property(e => e.Organizador).HasColumnName("organizador");

                entity.Property(e => e.Responsavel).HasColumnName("responsavel");
            });

            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.ToTable("usuarios");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.DataCadastro).HasMaxLength(6);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using suaBaladaAqui.Models;

namespace suaBaladaAqui.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/SuaBaladaAquiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using suaBaladaAqui.Models;
using suaBaladaAqui.ViewsModels;

namespace suaBaladaAqui.Controllers
{
    public class SuaBaladaAquiController : Controller
    {
        private int elementosPorPagina = 9; //valor contante
        private int elementosIgnorados = 0;

        private readonly suaBaladaAquiContext _context;

        public SuaBaladaAquiController(suaBaladaAquiContext context){
            _context = context;
        }

        public async Task<ActionResult> Index(int? id)
        {
        
            ViewBag.paginaAtual = 0;

             if (id != null)
            {
                ViewBag.paginaAtual = (int)(id - 1);
                elementosIgnorados = (int)(elementosPorPagina * (id - 1));
            }

            var query = (from evento in _context.Eventos
                        where evento.DataEvento >= DateTime.Today
                        //(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day + 1)
                        orderby evento.DataEvento
                        select new boxBaladaViewsModels(evento.Evento1, evento.DataEvento.ToString("dd/MM"), evento.Cidade, 
                        evento.LocalName, evento.Imagem ));

            ViewBag.numeroBaladas = await _context.Eventos.CountAsync();
            ViewBag.numeroPaginas = Math.Ceiling((double)ViewBag.numeroBaladas / (double)elementosPorPagina);
                        

            return View(await query.AsNoTracking().Skip(elementosIgnorados).Take(elementosPorPagina).ToListAsync());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Pesquisa([Bind("tipo")] string _tipo)
        {

            var tipo = "";
             if (ModelState.IsValid)
             {
                 tipo = _tipo;
             }
            /*if (usuariosModel == null)
            {
                return NotFound();
            }*/
            
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - suaBaladaAqui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/suaBaladaAqui.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark bg-gradient 
        box-shadow mb-0">
            <div class="container">
                <a class="navbar-brand text-light fw-bold" asp-area="" asp-controller="SuaBaladaAqui" asp-action="Index">suaBaladaAqui</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contato</a>
                        </li>-->
                    </ul>
                </div> 
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark bg-gradient">
        <div class="container fw-bold text-light">
            &copy; 2022 - suaBaladaAqui <!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Contato</a>-->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/SuaBaladaAqui/Index.cshtml
@model IEnumerable<suaBaladaAqui.ViewsModels.boxBaladaViewsModels>;

@{
    ViewData["Title"] = "suaBaladaAqui";
    var paginas = 0;
    var ativo = "";
}

<!-- Corousel -->
<div class="row">
    <div class="col-sm-12 position-relative">
        <div id="carouselSlides" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/img/festa3.jpg" class="d-block w-100 position-absolute top-50 start-50 translate-middle" alt="suaBaladaAqui">  
                    <div class="carousel-caption d-none d-md-block text-start">
                        <h5 class="text-warning">As melhores Baladas da região você encontra aqui!</h5>
                        <p class="fs-4 text">Procurando algo para sair da rotina? Então você está no lugar certo!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="~/img/festa2.jpg" class="d-block w-100 position-absolute top-50 start-50 translate-middle" alt="suaBaladaAqui">
                    <div class="carousel-caption d-none d-md-block text-start">
                        <h5 class="text-warning">As melhores Baladas da região você encontra aqui!</h5>
                        <p class="fs-4 text">Procurando algo para sair da rotina? Então você está no lugar certo!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="~/img/festa1.jpg" class="d-block w-100 position-absolute top-50 start-50 translate-middle" alt="suaBaladaAqui">
                    <div class="carousel-caption d-none d-md-block text-start">
                        <h5 class="text-warning">As melhores Baladas da região você encontra aqui!</h5>
                        <p class="fs-4 text">Procurando algo para sair da rotina? Então você está no lugar certo!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Pesquisa -->
<!--<div class="row">
    <div class="col-sm-12 bg-light br-gradient">
        <form asp-action="Pesquisa" method="post" class="w-75 mx-auto py-3" >
            <div class="row g-3 align-items-center justify-content-evenly">
                <div class="col-auto form-group w-25">
                    <select asp-for="tipo" class="form-select" aria-label="Default select example">
                        <option value="Evento1" selected>Pesquisar por Nome</option>
                        <option value="Cidade">Pesquisar por Cidade</option>
                    </select>
                </div>
                <div class="col-auto form-group input-group w-25">
                    <input type="text" class="form-control" placeholder="" aria-label="" aria-describedby="button-addon2">
                    <button type="submit" class="btn btn-outline-secondary" type="button">Pesquisar</button>
                </div>
            </div>
        </form>
    </div>
</div>-->

<!-- Conteúdo -->
<div class="row justify-content-center">  
    <div class="col-sm-12 py-5 w-75 bg-light bg-gradient">
        <div class="row row-cols-sm-3">
            @foreach (var evento in Model)
            {
                <div class="col-sm text-center">
                    <figure class="figure foto-conteudo">
                        <a data-bs-toggle="modal" data-bs-target="#Model" 
                        data-bs-target="#Modal" data-bs-whatever="@Html.DisplayFor(modelItem => evento.Imagem)">
                            <img src="@Html.DisplayFor(modelItem => evento.Imagem)" class="figure-img img-fluid rounded" alt="...">
                        </a>
                        <figcaption class="figure-caption text-end">
                            <span class="fs-6 badge rounded-pill bg-success">
                                @Html.DisplayFor(modelItem => evento.DataEvento)
                            </span>
                            <h5 id="festa-nome" class="fs-4 mb-3 text-dark">
                                @Html.DisplayFor(modelItem => evento.Evento1)
                            </h5>
                            <p id="cid" class="fs-6 text-muted mb-0">
                                @Html.DisplayFor(modelItem => evento.Cidade)
                            </p>
                            <p class="fs-5 text-primary">
                                Local: 
                                <span id="local" class="text-dark">
                                   @Html.DisplayFor(modelItem => evento.LocalName)
                                </span>
                            </p>
                        </figcaption>
                    </figure>
                </div> 
            }
         </div>
    </div>
</div>

<!-- Paginação -->
<div class="row">
    <div class="col-sm-12 bg-light bg-gradient">
        <nav class="w-75 mx-auto">
            <ul class="pagination justify-content-center">
                @for(var pags=0; pags<ViewBag.numeroPaginas; pags++)
                {
                    paginas++;
                    if(pags == ViewBag.paginaAtual)
                    {
                        ativo = "active";
                    }else{
                        ativo = "";
                    }
                    
                    <li class="page-item @ativo">
                        <a class="page-link" asp-controller="SuaBaladaAqui" asp-action="Index" asp-route-id="@paginas">
                            @paginas
                        </a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

<!-- Button trigger modal -->

<!-- Modal -->
@foreach (var evento in Model)
{
    <div class="modal fade" id="Model" tabindex="-1" aria-labelledby="ModalImg" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img src="@Html.DisplayFor(modelItem => evento.Imagem)" class="w-100" alt="...">
            </div>
            </div>
        </div>
    </div>
}